function plot_logSens_vs_error(robustness)
% plot the log-sensitivity vs error based on robustness 
% input: robustness -- data structure generated by calc_sensitivity
% output: plot
semilogy(robustness.error,robustness.logSensitivity.Controller,'r.',robustness.error,robustness.logSensitivity.Hamiltonian,'b.'), 
xlabel('error (infidelity)'), ylabel('log sensitivity'), legend('controller','couplings')
grid on, xlim([0 0.1])
